development:
  adapter: postgresql
  host: localhost
  username: rails-dev
  password: rails-dev
  database: app-dev

test: &test
  adapter: postgresql
  host: localhost
  username: rails-test
  password: rails-test
  database: app-test

production:
  adapter: postgresql
  host: localhost

cucumber:
  <<: *test